version: '3.1'

services:
  mi_mongo_db:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./databases/mongo:/data/db

  mi_maria_db:
    container_name: mariadb
    image: mariadb:10.6.14
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MARIA_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MARIA_DATABASE}"

    volumes:
      - ./databases/maria:/var/lib/mysql

  mi_express_server:
    container_name: express
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:4000
    environment:
      MONGO_DATABASE: "${MONGO_DATABASE}"
      MONGO_HOST: mi_mongo_db
      MONGO_PORT: 27017

      MARIA_HOST: mi_maria_db
      MARIA_ROOT_PASSWORD: "${MARIA_ROOT_PASSWORD}"
      MARIA_DATABASE: "${MARIA_DATABASE}"
      SQL_DIALECT: "${SQL_DIALECT}"

    depends_on:
      - mi_mongo_db

    volumes:
      - ./server:/segundo_parcial
      - /segundo_parcial/node_modules
